// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TitleCommandPosition","status":true,"description":"Changes the position of the title command window.","parameters":{"Offset X":"-300","Offset Y":"110","Width":"240","Background":"0"}},
{"name":"MrTS_PartyManager","status":true,"description":"Allows to check and change your party.","parameters":{"In Menu":"False","Command Name":"Party","Party Text":"Party","Members Text":"Members","Required Text":"Required:","Draw TP":"False"}},
{"name":"YED_WordWrap","status":true,"description":"v1.0.0 This plugin provides word wrap feature, so that a long text will be properly broken down into lines.","parameters":{}}
];
